rabbit:
  extends:
    file: common.yml
    service: rabbit

psql:
  extends:
    file: common.yml
    service: psql

mongo:
  extends:
    file: common.yml
    service: mongo

dkobo:
  extends:
    file: common.yml
    service: dkobo
#  links:
#    - psql
#    - rabbit
#    - kobocat
  volumes:
    - "../bigvol:/mnt"

kobocat:
  extends:
    file: common.yml
    service: kobocat
#  links:
#    - psql
#    - mongo
#    - rabbit
  volumes:
    - "../bigvol:/mnt"
