# copyleft 2015 teodorescu.serban@gmail.com
PSQL_ADMIN=${PSQL_ADMIN}
KOBO_PSQL_DB_NAME=${KOBO_PSQL_DB_NAME}
KOBO_PSQL_DB_USER=${KOBO_PSQL_DB_USER}
KOBO_PSQL_DB_PASS=${KOBO_PSQL_DB_PASS}
DATABASE_SERVER_IP=${DATABASE_SERVER_IP}
DATABASE_SERVER_PORT=${DATABASE_SERVER_PORT}
DATABASE_URL=${DATABASE_URL}
BROKER_URL=${BROKER_URL}
KOBOCAT_BROKER_URL=${BROKER_URL}
KOBOCAT_MONGO_HOST=${KOBOCAT_MONGO_HOST}
KOBOCAT_MONGO_PORT=${KOBOCAT_MONGO_PORT}
KOBOCAT_MONGO_NAME=${KOBOCAT_MONGO_NAME}
KOBOCAT_MONGO_USER=${KOBOCAT_MONGO_USER}
KOBOCAT_MONGO_PASS=${KOBOCAT_MONGO_PASS}
