# copyleft 2015 teodorescu.serban@gmail.com
DJANGO_SETTINGS_MODULE=${KOBOCAT_DJANGO_SETTINGS_MODULE}
DJANGO_DEBUG=${KOBOCAT_DJANGO_DEBUG}
DJANGO_LIVE_RELOAD=${KOBOCAT_DJANGO_LIVE_RELOAD}
DJANGO_SITE_ID=${KOBOCAT_DJANGO_SITE_ID}
DJANGO_SECRET_KEY=${KOBOCAT_DJANGO_SECRET_KEY}
DJANGO_SETTINGS_MODULE=${KOBOCAT_DJANGO_SETTINGS_MODULE}
PYTHONPATH=${PYTHONPATH}
