
# =======
KPI_PREFIX=${KPI_URI_PREFIX}
KOBO_USE_MINIFIED_SCRIPTS=${KOBO_USE_MINIFIED_SCRIPTS}
KOBOCAT_URL=${KOBOCAT_URL}
KOBOCAT_INTERNAL_URL=${KOBOCAT_INTERNAL_URL}
DKOBO_PREFIX=${DKOBO_PREFIX}
KOBO_SURVEY_PREVIEW_EXPIRATION=${KOBO_SURVEY_PREVIEW_EXPIRATION}
ENKETO_SERVER=${ENKETO_SERVER}
ENKETO_PREVIEW_URI=${ENKETO_PREVIEW_URI}
EMAIL_BACKEND=${EMAIL_BACKEND}
DEFAULT_FROM_EMAIL=${DEFAULT_FROM_EMAIL}
AWS_ACCESS_KEY_ID=${AWS_SES_ACCESS_KEY_ID}
AWS_SECRET_ACCESS_KEY=${AWS_SES_SECRET_ACCESS_KEY}
AWS_SES_REGION_NAME=${AWS_SES_REGION_NAME}
AWS_SES_REGION_ENDPOINT=${AWS_SES_REGION_ENDPOINT}

# =======
# Remove "KPI_" prefix from variables.
LIVERELOAD_SCRIPT=${KPI_LIVERELOAD_SCRIPT}
BROKER_URL=${KPI_BROKER_URL}
DJANGO_DEBUG=${KPI_DJANGO_DEBUG}
RAVEN_DSN=${KPI_RAVEN_DSN}
