KOBO_PREFIX=${KOBO_PREFIX}
KOBO_DOMAIN=${KOBO_DOMAIN}
KOBOFORM_SERVER_ADDR=${KOBOFORM_SERVER_ADDR}
KOBOFORM_SERVER_PORT=${KOBOFORM_SERVER_PORT}
KOBOCAT_SERVER_ADDR=${KOBOCAT_SERVER_ADDR}
KOBOCAT_SERVER_PORT=${KOBOCAT_SERVER_PORT}
