# copyleft 2015 teodorescu.serban@gmail.com

BASE_DIR=${BASE_DIR}
SRC_DIR=${SRC_DIR}
PYTHONPATH=${PYTHONPATH}

CSRF_COOKIE_DOMAIN=${CSRF_COOKIE_DOMAIN}
DATABASE_URL=${DATABASE_URL}
DJANGO_SECRET_KEY=${DJANGO_SECRET_KEY}
