# copyleft 2015 teodorescu.serban@gmail.com
DJANGO_SETTINGS_MODULE=${KOBOFORM_DJANGO_SETTINGS_MODULE}
DJANGO_DEBUG=${KOBOFORM_DJANGO_DEBUG}
DJANGO_LIVE_RELOAD=${KOBOFORM_DJANGO_LIVE_RELOAD}
DJANGO_SITE_ID=${KOBOFORM_DJANGO_SITE_ID}
DJANGO_SECRET_KEY=${KOBOFORM_DJANGO_SECRET_KEY}
DJANGO_SETTINGS_MODULE=${KOBOFORM_DJANGO_SETTINGS_MODULE}
PYTHONPATH=${PYTHONPATH}
PATH=$PATH:./node_modules/.bin
