# copyleft 2015 teodorescu.serban@gmail.com
PSQL_ADMIN=${PSQL_ADMIN}
KOBO_PSQL_DB_NAME=${KOBO_PSQL_DB_NAME}
KOBO_PSQL_DB_USER=${KOBO_PSQL_DB_USER}
KOBO_PSQL_DB_PASS=${KOBO_PSQL_DB_PASS}
PSQL_HOST=${PSQL_HOST}
PSQL_PORT=${PSQL_PORT}
DATABASE_URL=${DATABASE_URL}
# KOBOFORM_BROKER_URL=${KOBOFORM_BROKER_URL}  # Will eventually want to connect Celery to the new KoBoForm.
KOBOCAT_BROKER_URL=${KOBOCAT_BROKER_URL}
KOBOCAT_MONGO_HOST=${KOBOCAT_MONGO_HOST}
KOBOCAT_MONGO_PORT=${KOBOCAT_MONGO_PORT}
KOBOCAT_MONGO_NAME=${KOBOCAT_MONGO_NAME}
KOBOCAT_MONGO_USER=${KOBOCAT_MONGO_USER}
KOBOCAT_MONGO_PASS=${KOBOCAT_MONGO_PASS}
