BASE_DIR=${BASE_DIR}
SRC_DIR=${SRC_DIR}
PYTHONPATH=${PYTHONPATH}

KOBO_SERVER_IP=${KOBO_WB_SERVER_IP}

KOBOFORM_SERVER_PORT=${KOBOFORM_SERVER_PORT}
KOBOFORM_URL=http://${KOBO_WB_SERVER_IP}:${KOBOFORM_SERVER_PORT}


KOBOCAT_SERVER_PORT=${KOBOCAT_SERVER_PORT}
KOBOCAT_URL=http://${KOBO_WB_SERVER_IP}:${KOBOCAT_SERVER_PORT}
KOBOCAT_INTERNAL_URL=http://${KOBO_WB_SERVER_IP}:${KOBOCAT_SERVER_PORT}
#http://localhost:8001

ENKETO_EXPRESS_SERVER_PORT=${ENKETO_EXPRESS_SERVER_PORT}

KOBOCAT_REPO=${KOBOCAT_REPO}
KOBOCAT_BRANCH=${KOBOCAT_BRANCH}
KOBOCAT_PATH=${KOBOCAT_PATH}

KOBOCAT_TEMPLATES_REPO=${KOBOCAT_TEMPLATES_REPO}
KOBOCAT_TEMPLATES_BRANCH=${KOBOCAT_TEMPLATES_BRANCH}
KOBOCAT_TEMPLATES_PATH=${KOBOCAT_TEMPLATES_PATH}

KOBOFORM_PREVIEW_SERVER=${KOBOFORM_PREVIEW_SERVER}
KOBOFORM_REPO=${KOBOFORM_REPO}
KOBOFORM_BRANCH=${KOBOFORM_BRANCH}
KOBOFORM_PATH=${KOBOFORM_PATH}

DEFAULT_KOBO_USER=${DEFAULT_KOBO_USER}
DEFAULT_KOBO_PASS=${DEFAULT_KOBO_PASS}

# Enketo-Express-related configurations.
ENKETO_EXPRESS_REPO_DIR=${ENKETO_EXPRESS_REPO_DIR}
ENKETO_EXPRESS_UPDATE_REPO=${ENKETO_EXPRESS_UPDATE_REPO}

# For KoBoForm.
ENKETO_SERVER=${ENKETO_SERVER}
ENKETO_PREVIEW_URI=${ENKETO_PREVIEW_URI}

# For KoBoCat.
ENKETO_URL=${ENKETO_URL}
ENKETO_API_ROOT=${ENKETO_API_ROOT}
ENKETO_OFFLINE_SURVEYS=${ENKETO_OFFLINE_SURVEYS}
ENKETO_API_ENDPOINT_PREVIEW=${ENKETO_API_ENDPOINT_PREVIEW}
ENKETO_PROTOCOL=${ENKETO_PROTOCOL}
ENKETO_API_TOKEN=${ENKETO_API_TOKEN}

# django settings specific details
DJANGO_LIVE_RELOAD=${DJANGO_LIVE_RELOAD}
DJANGO_SITE_ID=${DJANGO_SITE_ID}

CSRF_COOKIE_DOMAIN=${CSRF_COOKIE_DOMAIN}
